version: '1.0.0.{build}'
configuration:
  - Debug
  - Release
build_script:
  - echo "Building for %CONFIGURATION%"
  - dotnet restore
  - dotnet build -c %CONFIGURATION%
test_script:
  - ps: dotnet test .\NShim.Tests\NShim.Tests.csproj
  - ps: if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
cache:
  - '%USERPROFILE%\.nuget\packages'
deploy:
  - provider: NuGet
    api_key:
      secure: E/KmrX24WpeHiBFzDXDcV97johIetz+eRsN/DsQxzQ4tMH+VUdPVzBTwaQ/ZuxrS
    skip_symbols: false
    artifact: /.*\.nupkg/
